# Generated by Django 3.0.6 on 2020-05-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='invite',
            field=models.CharField(default='ABCDEF12', max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
